name: skezik

description: skezik znajdz zlecenie.

publish_to: 'none' 


version: 2.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  equatable: ^2.0.5
  meta: ^1.8.0
  flutter_countdown_timer: ^4.1.0
  intl: ^0.18.0
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "image/S.jpg"
  min_sdk_android: 21


flutter:


  uses-material-design: true


